config/routes.rb
Sg::Application.routes.draw do

  root 'clients#index'
  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'create_user' => 'users#new', as: 'create_user'
  resources :pages
  resources :users
  resources :sessions

  resources :materials
  resources :part_types
  resources :panel_models

  resources :clients do
    resources :jobs
  end

  resources :panels do
    resources :parts
  end
  resources :structures do
    resources :panels
  end

  resources :manufacturing_jobs do
    resources :nest_runs
  end
  resources :phases do
    resources :structures
    resources :manufacturing_jobs
  end

  resources :jobs do
    resources :phases
  end

  resources :nest_runs do
    resources :nests
  end
  resources :nests do
    resources :nest_objects
  end
end

app/models/manufacturing_job.rb
class ManufacturingJob < ActiveRecord::Base
  belongs_to :phase
  has_many :nest_runs, dependent: :destroy
  has_many :nests, through: :nest_runs
  has_many :nest_objects, through: :nests
  has_and_belongs_to_many :parts

  after_create do
    # create nest runs
    NestRunService.new.create(manufacturing_job: self, parts: parts)
  end

  before_destroy :update_manufactured_statuses

  def progress
    nests = self.nests
    tasks = nests.length
    completed = nests.where(is_manufactured: true).length.to_f
    ratio = ((completed / tasks) * 100).to_f
    return 0 if ratio.nan?
    ratio = ratio > 0 ? ratio : 0
    ratio.round(0)
  end

  def percentage
    prog = progress
    return 5 if prog > 0 && prog < 5
    5 * (prog / 5).round
  end

  def update_manufactured_statuses
    parts.each do |part|
      # update parts
      part.update_manufactured_status
      # update panels
      part.panel.update_manufactured_status
    end
  end

  def mfg_job_name
    return nil unless name
    "#{name} Job"
  end
end

app/controllers/manufacturing_jobs_controller.rb
class ManufacturingJobsController < ApplicationController
  before_filter :load_lineage
  before_action :set_manufacturing_job, only: [:show, :edit, :update, :destroy]

  # GET /manufacturing_jobs
  # GET /manufacturing_jobs.json
  def index
    @manufacturing_jobs = ManufacturingJob.all
    @manufacturing_jobs_index = true
    @manufacturing_jobs = ManufacturingJob.new
    redirect_to job_phase_path(@job,@phase)
  end

  # GET /manufacturing_jobs/1
  # GET /manufacturing_jobs/1.json
  def show
    @manufacturing_jobs_show = true
  end

  # GET /manufacturing_jobs/new
  def new
    @manufacturing_job = ManufacturingJob.new(manufacturing_job_params)
    @manufacturing_jobs_new = true
  end

  # GET /manufacturing_jobs/1/edit
  def edit
    @manufacturing_jobs_edit = true
  end

  # POST /manufacturing_jobs
  # POST /manufacturing_jobs.json
  def create
    @manufacturing_job = ManufacturingJob.new(manufacturing_job_params)

    respond_to do |format|
      if @manufacturing_job.save
        format.js   {}
        format.html { redirect_to phase_manufacturing_job_path(@phase, @manufacturing_job), notice_success: 'Manufacturing job created!' }
        format.json { render action: 'show', status: :created, location: @manufacturing_job }
      else
        format.html { render action: 'new' }
        format.json { render json: @manufacturing_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufacturing_jobs/1
  # PATCH/PUT /manufacturing_jobs/1.json
  def update
    respond_to do |format|
      if @manufacturing_job.update(manufacturing_job_params)
        format.html { redirect_to phase_manufacturing_job_path(@phase, @manufacturing_job), notice_success: 'Manufacturing job updated!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @manufacturing_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturing_jobs/1
  # DELETE /manufacturing_jobs/1.json
  def destroy
    @manufacturing_job.destroy
    respond_to do |format|
      format.html { redirect_to job_phase_path(@job, @phase) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def load_lineage
      @phase = Phase.find(params[:phase_id])
      @job = Job.find(@phase.job_id)
      @client = Client.find(@job.client_id)
    end

    def set_manufacturing_job
      @manufacturing_job = ManufacturingJob.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manufacturing_job_params
      params.fetch(:manufacturing_job, {}).permit(:phase_id, :name, :date, part_ids: [])
    end
end

app/helpers/manufacturing_jobs_helper.rb
module ManufacturingJobsHelper
end

app/views/manufacturing_jobs/_footer.html.erb
<footer class="footer">
<div class="row">
  <div class="col-xs-12">
    <% if @manufacturing_jobs_show || @manufacturing_jobs_new || @manufacturing_jobs_index%>
      <%= link_to job_phase_path(@job,@phase), :class => 'btn btn-default' do %>
        <span class="glyphicon glyphicon-arrow-left"></span> Back to Phase <%= @phase.name %>
      <% end %>
    <% elsif @manufacturing_jobs_edit %>
      <%= link_to phase_manufacturing_job_path(@phase, @manufacturing_job), :class => 'btn btn-default' do %>
        <span class="glyphicon glyphicon-arrow-left"></span> Back to <%= @manufacturing_job.mfg_job_name %>
      <% end %>
    <% end %>
  </div>
</div>
</footer>

app/views/manufacturing_jobs/_form.html.erb
<%= simple_form_for [@phase, @manufacturing_job], :html => {:class => "validate"} do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true, :class => 'form-control' %>
  </div>
  <%= f.hidden_field :part_ids %>
  <% if @manufacturing_jobs_new %>
    <% ordered_parts = @phase.parts.joins(:panel => :structure).order('structures.name ASC') %>
    <div class="form-group">
      <div class="btn-group">
        <%= f.collection_select :part_ids, ordered_parts, :id, :scope_name, {}, {:multiple => true, :data => {type: 'Parts'}, :class => 'form-control multiselect-all'} %>
        <button class="multiselect-select-all btn btn-primary">Select All</button>
      </div>
    </div>
  <% else %>
    <%= f.hidden_field :phase_id, :value => @phase.id %>
  <% end %>

  <div class="form-group text-right">
    <%= f.submit "Submit", :data => {'loading-text' => 'Submitting...'}, :class => 'btn btn-success' %>
    <% if @manufacturing_jobs_edit %>
      <% if @manufacturing_job.nests.where(:is_manufactured => true).first %>
        <span class="btn btn-danger disabled">Remove</span><br>
        <small><em>This Job has manufactured Nests.</em> <br>Mark them as unmanufactured before you remove this Job.</small>
      <% else %>
        <%= link_to 'Remove', phase_manufacturing_job_path(@phase,@manufacturing_job), method: :delete, :class => "btn btn-danger", data: { confirm: 'Are you sure you want to delete this manufacturing job?' } %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/manufacturing_jobs/_header.html.erb
<div class="page-header">
  <h2>
    <% if @manufacturing_jobs_show %>
      <span class="progress-radial big progress-<%=@manufacturing_job.percentage%>"></span> <%= @manufacturing_job.mfg_job_name %>
      <% if @current_role == 'admin' %>
      <%= link_to edit_phase_manufacturing_job_path(@phase,@manufacturing_job), :class => 'btn btn-default btn-xs' do %>
        <span class="glyphicon glyphicon-pencil"></span> Edit
      <% end %>
      <% end %>
    <% elsif @manufacturing_jobs_new %>
      New Mfg Job
    <% elsif @manufacturing_jobs_edit %>
      Editing <%= @manufacturing_job.mfg_job_name %>
    <% elsif @manufacturing_jobs_index %>
      Phase <%= @phase.name %> <small>Mfg Jobs</small>
    <% end %>
  </h2>
</div>

app/views/manufacturing_jobs/_inline_manufacturing_job_form.html.erb
<%= simple_form_for([@phase,@new_manufacturing_job], :html => {:class => "validate"}, remote: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true, :class => "form-control" %>
  </div>

  <div class="form-group">
    <% ordered_parts = @phase.parts.joins(:panel => :structure).order('structures.name ASC, panels.side_position ASC') %>
    <div class="btn-group">
      <%= f.collection_select :part_ids, ordered_parts, :id, :scope_name, {}, {:multiple => true, :data => {type: 'Parts'}, :class => 'form-control multiselect-select'} %>
      <button class="multiselect-select-all btn btn-primary">Select All</button>
    </div>
    <%= f.submit "Generate", :data => {'loading-text' => 'Generating...'}, :class => "btn pull-right btn-success" %>
  </div>



  <div class="form-group text-right">
  <%= f.hidden_field :phase_id, :value => @phase.id %>
  </div>

  <div id="multiselect-values" class="alert alert-success">
    <h4>Queued for MFG</h4>
    <em>Nothing selected</em>
  </div>

<% end %>

app/views/manufacturing_jobs/_manufacturing_job.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <div class="row">
        <div class="col-xs-8">
          <h4>
            <div class="progress-radial progress-<%= manufacturing_job.percentage %>"></div>
            <%= link_to 'Mfg Job ' + manufacturing_job.name, phase_manufacturing_job_path(@phase,manufacturing_job) %>
          </h4>
        </div>
        <div class="col-xs-4 text-right">
          <a data-toggle="collapse" data-parent="#manufacturing_jobs" href="#mfg_job_<%= manufacturing_job.id %>" class="reveal collapsed btn btn-xs btn-default">
            <span class="show-text">More <span class="glyphicon glyphicon-chevron-down"></span></span><span class="hide-text">Less <span class="glyphicon glyphicon-chevron-up"></span></span>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div id="mfg_job_<%= manufacturing_job.id %>" class="panel-collapse collapse">
    <div class="panel-body">
      <%#= render 'manufacturing_jobs/manufacturing_job_progress', manufacturing_job: manufacturing_job %>
      <h5>Runs:</h5>
      <ul class="list-unstyled">
      <% manufacturing_job.nest_runs.each do |nest_run| %>
        <li><%= link_to nest_run.material.name, manufacturing_job_nest_run_path(manufacturing_job,nest_run), :class => "" %></li>
      <% end %>
      </ul>
      <h5>Structures:</h5>
      <p>
      <% structures = Structure.where(:phase_id => @phase.id) %>
      <% structures = structures.sort_by(&:name_number) %>
      <% structures.each do |structure| %>
        <% if structure.manufacturing_jobs.include?(manufacturing_job.id) %>
          <%= link_to structure.name, phase_structure_path(@phase,structure), :class => 'btn btn-primary btn-sm' %>
        <% end %>
      <% end %>
      </p>
      <p><small><%= manufacturing_job.parts.length %> Parts / Created <%= full_time(manufacturing_job.created_at) %></small></p>
    </div>
  </div>
</div>

app/views/manufacturing_jobs/_manufacturing_job_progress.html.erb
<%
percentage = manufacturing_job.progress

if percentage < 33 then progress_class = 'progress-bar-danger'
elsif percentage < 66 then progress_class = 'progress-bar-warning'
elsif percentage < 100 then progress_class = 'progress-bar-primary'
else progress_class = 'progress-bar-success'
end

%>
<div class="progress active progress-striped">
  <div class="progress-bar <%= progress_class %>" role="progressbar" aria-valuenow="<%= percentage %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= percentage %>%;">
    <% if percentage < 100 %>
      <span class="progress-status"><%= percentage %>%</span>

    <% else %>
      <span class="progress-status">Complete</span>
    <% end %>
      <span class="sr-only"><%= percentage %>%</span>
    </div>
</div>

app/views/manufacturing_jobs/_nest_runs.html.erb
<%# ordered_nest_runs = @manufacturing_job.nest_runs.sort_by{|nr| - nr.nests.count } %>
<% ordered_nest_runs = @manufacturing_job.nest_runs.sort_by{|nr| nr.material.id } %>
<% ordered_nest_runs.each_with_index do |nest_run, index| %>


  <% material = nest_run.material %>

  <div class="panel panel-default">

  <% if material.material_type == 'length' %>
    <div class="panel-heading">

      <h3>
        <span class="progress-radial progress-<%=nest_run.percentage%>"></span>
        <%= link_to nest_run.nest_material_name, manufacturing_job_nest_run_path(@manufacturing_job,nest_run) %>
        <!--<br> <small><%= nest_run.progress %>% / <%= nest_run.nests.length %> Nests / Total Waste: <%= get_feet(nest_run.waste_in_inches) %> (or <%= nest_run.waste_in_material_quantity %> lengths of <%= get_feet(nest_run.material.length_options.first.to_i) %> <%= nest_run.material.name %>)</small> -->
        <small>
          <%= pluralize(nest_run.nests.length, 'Length') %>
          <br>
          Total Waste: <%= get_feet(nest_run.waste_in_inches) %> (or <%= nest_run.waste_in_material_quantity %> lengths of <%= get_feet(nest_run.material.length_options.first.to_i) %> <%= nest_run.material.name %>)
        </small>
      </h3>
    </div>
    <div class="panel-body">
      <div class="row">
      <% nest_run.nests.each_with_index do |nest, index| %>

      <% if nest.is_manufactured == true %>
        <% manufacture_status = "<span class=\"circle success\"></span>".html_safe %>
      <% else %>
        <% manufacture_status = "<span class=\"circle danger\"></span>".html_safe %>
      <% end %>

      <div class="col-md-3">

        <div class="thumbnail">
          <div class="thumbnail-title">
            <h4><%= manufacture_status %> <%= link_to 'Length '+ nest.number_index, nest_run_nest_path(nest_run,nest) %> (<%= get_feet(nest.length) %>)</h4>
          </div>

          <div class="nest">
            <%= nest.map_svg.html_safe %>
          </div>

          <div class="caption text-right">
            <h4><small><%= get_feet(nest.waste_in_inches) %> of waste</small></h4>
          </div>

        </div>

      </div> <!-- end col -->
      <% if (index + 1) % 4 == 0 %>
        </div> <!-- end row -->
        <div class="row">
      <% end %>
      <% end %>
    </div> <!-- end row -->
  </div> <!-- panel body -->

  <% else %>

    <div class="panel-heading">
      <h3>
        <span class="progress-radial progress-<%=nest_run.percentage%>"></span>
        <%= link_to nest_run.nest_material_name, manufacturing_job_nest_run_path(@manufacturing_job,nest_run) %>
        <!-- <br><small><%= nest_run.progress %>% / <%= nest_run.nests.length %> Nests / Total Waste: <%= get_square_feet(nest_run.waste_in_inches) %> (or <%= nest_run.waste_in_material_quantity %> sheets of <%= nest_run.material.name %>)</small> -->
        <small>
          <%= pluralize(nest_run.nests.length, 'Sheet') %>
          <br>
          Total Waste: <%= get_square_feet(nest_run.waste_in_inches) %> (or <%= nest_run.waste_in_material_quantity %> sheets of <%= nest_run.material.name %>)
        </small>
      </h3>
    </div>

    <div class="panel-body">
      <div class="row">
      <% nest_run.nests.each_with_index do |nest, index| %>


        <% if nest.is_manufactured == true %>
          <% manufacture_status = "<span class=\"circle success\"></span>".html_safe %>
        <% else %>
          <% manufacture_status = "<span class=\"circle danger\"></span>".html_safe %>
        <% end %>

        <div class="col-md-3">
          <div class="thumbnail">

            <div class="thumbnail-title">
              <h4><%= manufacture_status %> <%= link_to 'Sheet '+ nest.number_index, nest_run_nest_path(nest_run,nest) %></h4>
            </div>

            <div class="nest">
              <%= nest.map_svg.html_safe %>
            </div>

            <div class="caption text-right">
              <h4><small><%= get_square_feet(nest.waste_in_inches) %> of waste</small>

              <button class="btn btn-xs btn-primary" data-toggle="modal" data-target="#<%= nest.id %>">
                Part File <span class="glyphicon glyphicon-zoom-in"></span>
              </button>

              <div class="modal fade" id="<%= nest.id %>" tabindex="-1" role="dialog" aria-labelledby="<%= nest.id %>_title" aria-hidden="true">
                <div class="modal-dialog big-modal">
                  <div class="modal-content">
                    <div class="modal-header text-left">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                      <h4 class="modal-title" id="<%= nest.id %>_title">Nest <%= nest.number_index %> / Part File</h4>
                      <a class="btn btn-xs btn-primary" href="<%= nest_run_nest_path(nest_run, nest) %>.svg" download="<%= nest_run_nest_path(nest_run, nest) %>.svg" title="<%= nest_run.manufacturing_job.name %>_<%= nest_run.material.name %>_<%= nest.number_index %>">Download SVG <span class="glyphicon glyphicon-download"></span></a>
                    </div>
                    <div class="modal-body text-center">
                      <%= nest.svg.html_safe %>
                    </div>
                  </div>
                </div>
               </div>
            </div>

          </div>

        </div> <!-- end col -->
        <% if (index + 1) % 4 == 0 %>
          </div> <!-- end row -->
          <div class="row">
        <% end %>
      <% end %>
    </div> <!-- end row -->

  </div> <!-- panel body -->

  <% end %>
  </div> <!-- panel -->
<% end %>

app/views/manufacturing_jobs/create.js.erb
// append in case of weak connection
$("<%= escape_javascript(render @manufacturing_job) %>").prependTo("#manufacturing_jobs");
// reload page
location.reload();

app/views/manufacturing_jobs/edit.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= render 'footer' %>

app/views/manufacturing_jobs/index.html.erb
<h4>Manufacturing Jobs</h4>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Phase</th>
      <th>Name</th>
      <th>Date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @manufacturing_jobs.each do |manufacturing_job| %>
      <tr>
        <td><%= manufacturing_job.phase_id %></td>
        <td><%= manufacturing_job.name %></td>
        <td><%= manufacturing_job.date %></td>
        <td class="text-right"><%= link_to 'Show', manufacturing_job, :class => "btn btn-xs btn-default" %> <%= link_to 'Edit', edit_manufacturing_job_path(manufacturing_job), :class => "btn btn-xs btn-primary" %> <%= link_to 'Remove', manufacturing_job, method: :delete, :class => "btn btn-xs btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manufacturing job', new_manufacturing_job_path, :class => 'btn btn-primary' %>

app/views/manufacturing_jobs/new.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= render 'footer' %>

app/views/manufacturing_jobs/show.html.erb
<%= render 'header' %>
<%= render 'nest_runs' %>
<%= render 'footer' %>