config/routes.rb
Sg::Application.routes.draw do

  root 'clients#index'
  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'create_user' => 'users#new', as: 'create_user'
  resources :pages
  resources :users
  resources :sessions

  resources :materials
  resources :part_types
  resources :panel_models

  resources :clients do
    resources :jobs
  end

  resources :panels do
    resources :parts
  end
  resources :structures do
    resources :panels
  end

  resources :manufacturing_jobs do
    resources :nest_runs
  end
  resources :phases do
    resources :structures
    resources :manufacturing_jobs
  end

  resources :jobs do
    resources :phases
  end

  resources :nest_runs do
    resources :nests
  end
  resources :nests do
    resources :nest_objects
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :jobs

  validates :name, presence: true

  def job_count
    1000 - jobs.count
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all.sort_by(&:job_count)
    @clients_index = true
    @no_top_nav = true
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @clients_show = true
    @no_top_nav = true
  end

  # GET /clients/new
  def new
    @client = Client.new(client_params)
    @clients_new = true
    @no_top_nav = true
  end

  # GET /clients/1/edit
  def edit
    @clients_edit = true
    @no_top_nav = true
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.create(client_params)
    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice_success: 'Client created!' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice_success: 'Client updated!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.fetch(:client, {}).permit(:name, :contact)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_footer.html.erb
<footer class="footer">
<div class="row">
  <div class="col-xs-12">
    <% if @clients_show || @clients_edit || @clients_new %>
      <%= link_to clients_path, :class => 'btn btn-default' do %>
        <span class="glyphicon glyphicon-arrow-left"></span> Back to Clients
      <% end %>
    <% elsif @clients_index %>
      <% if @clients.length > 0 %>

        <% if @current_role == 'admin' %>

          <%= link_to new_client_path, :class => 'btn btn-primary' do %>
            <span class="glyphicon glyphicon-plus"></span> New Client
          <% end %>

        <% end %>

      <% else %>

        <% if @current_role == 'admin' %>
          <h3>Nothing Yet. <%= link_to "Add a Client", new_client_path %> to get started.</h3>
        <% else %>
          <h3>Nothing Yet.</h3>
        <% end %>

      <% end %>

    <% end %>
  </div>
</div>
</footer>

app/views/clients/_form.html.erb
<%= simple_form_for @client, :html => {:class => "validate"} do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h4>
      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contact %><br>
    <%= f.text_area :contact, :class => "form-control" %>
  </div>
  <div class="form-group text-right">
      <%= f.submit "Submit", :data => {'loading-text' => 'Submitting...'}, :class => 'btn btn-success' %>
      <% if @clients_edit %>
        <% job_count = @client.jobs.length %>
          <% if job_count > 0 %>
            <span class="btn btn-danger disabled">Remove</span><br>
            <small><em>This Client has <%= pluralize(job_count, "Job") %></em> <br>Remove before you remove this Client.</small>
          <% else %>
            <%= link_to 'Remove', client_path(@client), method: :delete, :class => "btn btn-danger", data: { confirm: 'Are you sure?' } %>
          <% end %>
      <% end %>
  </div>
<% end %>

app/views/clients/_header.html.erb
<% if @clients_show || @clients_index %>
<div class="row">
  <div class="col-md-12 logo-top">
    <a href="<%= root_url %>"><img src="<%= root_url %>logo-dark.png" /></a>
  </div>
</div>
<% end %>
<div class="page-header">
  <h1>
    <% if @clients_show %>
      <%- title "#{@client.name}" %>
      <%= @client.name %>
      <% if @current_role == 'admin' %>
        <%= link_to edit_client_path(@client), :class => 'btn btn-default btn-xs' do %>
          <span class="glyphicon glyphicon-pencil"></span> Edit
        <% end %>
      <% end %>
    <% elsif @clients_new %>
      <%- title "New Client" %>
      New Client
    <% elsif @clients_edit %>
      <%- title "#{@client.name}" %>
      Editing <%= @client.name %>
    <% elsif @clients_index %>
      <%- title "Clients" %>
      Clients
    <% end %>
  <% if @clients_show  && @client.contact %>
  <br>
  <small><%= @client.contact %></small>
  <% end %>
  </h1>
</div>

app/views/clients/_jobs.html.erb
<% if @client.jobs.length > 0 %>
  <div class="row">
  <% client_jobs = @client.jobs.order('created_at DESC') %>
  <% client_jobs.each_with_index do |job, i| %>
    <div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>
            <%= link_to(job.name, client_job_path(@client, job), :class => "") %>
            <% if @current_role == 'admin' %>
              <%= link_to edit_client_job_path(@client, job), :class => 'btn btn-default btn-xs' do %>
                <span class="glyphicon glyphicon-pencil"></span> Edit
              <% end %>
            <% end %>
            <br>
            <small><%= job.location %></small>
          </h3>

        </div>
        <div class="panel-body">
          <% job_phases = job.phases.order('created_at DESC') %>
          <% job_phases.each do |phase| %>
            <h4>
              <span class="progress-radial progress-<%=phase.percentage%>"></span>
              <%= link_to 'Phase '+phase.name, job_phase_path(job, phase) %>
              <small><%= pluralize(phase.structures.length, "Structure") %></small>
            </h4>
          <% end %>
        </div>
      </div>
    </div>
    <% if (i+1) % 2 == 0 %>
  </div>
  <div class="row">
    <% end %>
  <% end %>
  </div>


  <% if @current_role == 'admin' %>
  <div class="row">
    <div class="col-xs-12">
    <%= link_to new_client_job_path(@client), :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span> Add Job
    <% end %>
    </div>
  </div>
  <% end %>

<% else %>

  <% if @current_role == 'admin' %>
    <h3>Nothing Yet. <%= link_to "Add a Job", new_client_job_path(@client) %> to get started.</h3>
  <% else %>
    <h3>Nothing Yet.</h3>
  <% end %>

<% end %>

app/views/clients/_list.html.erb
<% if @clients.count > 0 %>
  <div id="clients" class="panel-group">
    <% @clients.each do |client| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">
          <div class="row">
            <div class="col-xs-8">
              <h4>
                <%= link_to client.name, client_path(client) %>
                <small><%= client.contact %></small>
              </h4>
            </div>
            <div class="col-xs-4 text-right">
              <a data-toggle="collapse" data-parent="#clients" href="#client<%= client.id %>" class="reveal collapsed btn btn-xs btn-default">
                <span class="show-text">More <span class="glyphicon glyphicon-chevron-down"></span></span><span class="hide-text">Less <span class="glyphicon glyphicon-chevron-up"></span></span>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div id="client<%= client.id %>" class="panel-collapse collapse">
        <div class="panel-body">
          <div class="row">
            <% client_jobs = client.jobs %>
            <% client_jobs.each_with_index do |job, i| %>
              <div class="col-sm-6">
                <div class="block">
                  <div class="block-header">
                    <h3><%= link_to job.name, client_job_path(client,job) %></h3>
                  </div>
                  <% job_phases = job.phases.order('created_at DESC') %>
                  <% job_phases.each do |phase| %>
                    <h4>
                      <span class="progress-radial progress-<%=phase.percentage%>"></span>
                      <%= link_to "Phase " + phase.name, job_phase_path(job,phase) %> <small> <%= pluralize(phase.structures.count, "Structure") %></small>
                    </h4>
                  <% end %>
                </div>
              </div>
              <% if (i+1) % 2 == 0 %>
            </div>
            <div class="row">
              <% end %>
            <% end %>
            </div>
          </div>
        </div>
    </div>
    <% end %>
  </div>
<% else %>

  <% if @current_role == 'admin' %>
    <h3>Nothing Yet. <%= link_to "Add a Client", new_client_path() %> to get started.</h3>
  <% else %>
    <h3>Nothing Yet.</h3>
  <% end %>

<% end %>

app/views/clients/edit.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= render 'footer' %>

app/views/clients/index.html.erb
<%= render 'header' %>
<%= render 'list' %>
<%= render 'footer' %>

app/views/clients/new.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= render 'footer' %>

app/views/clients/show.html.erb
<%= render 'header' %>
<%= render 'jobs' %>
<%= render 'footer' %>