config/routes.rb
Sg::Application.routes.draw do

  root 'clients#index'
  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'create_user' => 'users#new', as: 'create_user'
  resources :pages
  resources :users
  resources :sessions

  resources :materials
  resources :part_types
  resources :panel_models

  resources :clients do
    resources :jobs
  end

  resources :panels do
    resources :parts
  end
  resources :structures do
    resources :panels
  end

  resources :manufacturing_jobs do
    resources :nest_runs
  end
  resources :phases do
    resources :structures
    resources :manufacturing_jobs
  end

  resources :jobs do
    resources :phases
  end

  resources :nest_runs do
    resources :nests
  end
  resources :nests do
    resources :nest_objects
  end
end

app/models/panel_model.rb
class PanelModel < ActiveRecord::Base
  has_many :panels, dependent: :destroy

  validates :name, presence: true
  has_attached_file :panel_model_image, styles: {
    large: '540x720>', medium: '480x480>', thumb: '240x240>'
  }, default_url: '/images/:style/missing.png'
end

app/controllers/panel_models_controller.rb
class PanelModelsController < ApplicationController
  before_action :set_panel_model, only: [:show, :edit, :update, :destroy]

  # GET /panel_models
  # GET /panel_models.json
  def index
    @panel_models = PanelModel.all
    @panel_models_index = true
    @no_top_nav = true
  end

  # GET /panel_models/1
  # GET /panel_models/1.json
  def show
    @panel_models_show = true
    @no_top_nav = true
  end

  # GET /panel_models/new
  def new
    @panel_model = PanelModel.new
    @panel_models_new = true
    @no_top_nav = true
  end

  # GET /panel_models/1/edit
  def edit
    @panel_models_edit = true
    @no_top_nav = true
  end

  # POST /panel_models
  # POST /panel_models.json
  def create
    @panel_model = PanelModel.create(panel_model_params)

    respond_to do |format|
      if @panel_model.save
        format.html { redirect_to @panel_model, notice_success: 'Panel model created!' }
        format.json { render action: 'show', status: :created, location: @panel_model }
      else
        format.html { render action: 'new' }
        format.json { render json: @panel_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /panel_models/1
  # PATCH/PUT /panel_models/1.json
  def update
    respond_to do |format|
      if @panel_model.update(panel_model_params)
        format.html { redirect_to @panel_model, notice_success: 'Panel model updated!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @panel_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /panel_models/1
  # DELETE /panel_models/1.json
  def destroy
    @panel_model.destroy
    respond_to do |format|
      format.html { redirect_to panel_models_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel_model
      @panel_model = PanelModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panel_model_params
      params.require(:panel_model).permit(:name, :description, :panel_model_image)
    end
end

app/helpers/panel_models_helper.rb
module PanelModelsHelper
end

app/views/panel_models/_footer.html.erb
<footer class="footer">
<div class="row">
  <div class="col-xs-12">
    <% if @panel_models_show || @panel_models_edit || @panel_models_new %>
      <%= link_to panel_models_path, :class => 'btn btn-default' do %>
        <span class="glyphicon glyphicon-arrow-left"></span> Back to Panel Models
      <% end %>
    <%# elsif @panel_models_index %>
      <%# if @current_role == 'admin' %>
        <%#= link_to new_panel_model_path, :class => 'btn btn-primary' do %>
          <!-- <span class="glyphicon glyphicon-plus"></span> New Panel Model -->
        <%# end %>
      <%# end %>
    <% end %>
  </div>
</div>
</footer>

app/views/panel_models/_form.html.erb
<%= simple_form_for @panel_model, :html => { :multipart => true, :class => "validate" } do |f| %>
  <%= f.error_notification %>

    <% if !@panel_models_edit %>
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, :required => true, :class => "form-control" %>
    </div>
    <% end %>

    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, :rows => '8', :class => "form-control" %>
    </div>

    <div class="form-group form-image-container">
    <%= f.label :panel_model_image, 'Image' %><br>
    <% if @panel_models_edit && @panel_model.panel_model_image.presence %>
      <div class="form-image-view">
        <%= image_tag @panel_model.panel_model_image.url(:thumb) %><br>
        <a href="#" class="replace-image">Replace</a>
      </div>
      <div class="form-image-field">
        <%= f.file_field :panel_model_image %>
      </div>
    <% else %>
      <%= f.file_field :panel_model_image %>
    <% end %>
    </div>

    <% if @panel_models_edit %>
      <%= f.hidden_field :name %>
    <% end %>

    <div class="form-group text-right">
      <%= f.submit "Submit", :data => {'loading-text' => 'Submitting...'}, :class => "btn btn-success" %>
    </div>

<% end %>

app/views/panel_models/_header.html.erb
<div class="page-header">
  <h2>
    <% if @panel_models_show %>
      <%= @panel_model.name %>
      <% if @current_role == 'admin' %>
        <%= link_to edit_panel_model_path(@panel_model), :class => 'btn btn-default btn-xs' do %>
          <span class="glyphicon glyphicon-pencil"></span> Edit
        <% end %>
      <% end %>
    <% elsif @panel_models_new %>
      New Panel Model
    <% elsif @panel_models_edit %>
      Editing <%= @panel_model.name %>
    <% elsif @panel_models_index %>
      Panel Models
    <% end %>
  </h2>
</div>

app/views/panel_models/_list.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @panel_models.each do |panel_model| %>
      <tr>
        <td><%= link_to panel_model.name, panel_model %></td>
        <% if panel_model.panel_model_image.presence %>
          <td>
            <button class="btn btn-xs btn-default" data-toggle="modal" data-target="#<%= panel_model.id %>">
              <span class="glyphicon glyphicon-picture"></span>
            </button>
            <div class="modal fade" id="<%= panel_model.id %>" tabindex="-1" role="dialog" aria-labelledby="<%= panel_model.id %>_title" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="<%= panel_model.id %>_title"><%= panel_model.name %></h4>
                  </div>
                  <div class="modal-body text-center">
                    <%= image_tag panel_model.panel_model_image.url(:large) %>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
          </td>
        <% else %>
          <td></td>
        <% end %>
        <td class="text-right">
          <% if @current_role == 'admin' %>
            <%= link_to edit_panel_model_path(panel_model), :class => 'btn btn-default btn-xs' do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/panel_models/_panel_model.html.erb
<p>
  <strong>Name:</strong>
  <%= @panel_model.name %>

</p>

<% if @panel_model.panel_model_image.presence %>
<p>
  <strong>Image:</strong><br>
  <%= image_tag panel_model.panel_model_image.url(:large) %>
</p>
<% end %>

app/views/panel_models/edit.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= render 'footer' %>

app/views/panel_models/index.html.erb
<%= render 'header' %>
<%= render 'list' %>
<%= render 'footer' %>

app/views/panel_models/new.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= render 'footer' %>

app/views/panel_models/show.html.erb
<%= render 'header' %>
<%= render @panel_model %>
<%= render 'footer' %>