config/routes.rb
Sg::Application.routes.draw do

  root 'clients#index'
  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'create_user' => 'users#new', as: 'create_user'
  resources :pages
  resources :users
  resources :sessions

  resources :materials
  resources :part_types
  resources :panel_models

  resources :clients do
    resources :jobs
  end

  resources :panels do
    resources :parts
  end
  resources :structures do
    resources :panels
  end

  resources :manufacturing_jobs do
    resources :nest_runs
  end
  resources :phases do
    resources :structures
    resources :manufacturing_jobs
  end

  resources :jobs do
    resources :phases
  end

  resources :nest_runs do
    resources :nests
  end
  resources :nests do
    resources :nest_objects
  end
end

app/models/material.rb
class Material < ActiveRecord::Base
  has_many :nest_runs
  has_many :part_types
  has_many :parts, through: :part_types

  validates :name, presence: true
  serialize :length_options, Array

  before_validation do |material|
    material.length_options.reject!(&:blank?) if material.length_options
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
    @materials_index = true
    @no_top_nav = true
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
    @materials_show = true
    @no_top_nav = true
  end

  # GET /materials/new
  def new
    @material = Material.new
    @materials_new = true
    @no_top_nav = true
  end

  # GET /materials/1/edit
  def edit
    @materials_edit = true
    @no_top_nav = true
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice_success: 'Material created!' }
        format.json { render action: 'show', status: :created, location: @material }
      else
        format.html { render action: 'new' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice_success: 'Material updated!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:name, :cut_spacing, :width, :height, :count, :length, :material_type, :length_options => [])
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_footer.html.erb
<footer class="footer">
<div class="row">
  <div class="col-xs-12">
    <% if @materials_show || @materials_edit || @materials_new %>
      <%= link_to materials_path, :class => 'btn btn-default' do %>
        <span class="glyphicon glyphicon-arrow-left"></span> Back to Materials
      <% end %>
    <%# elsif @materials_index %>
      <%# if @current_role == 'admin' %>
        <%#= link_to new_material_path, :class => 'btn btn-primary' do %>
          <!-- <span class="glyphicon glyphicon-plus"></span> New Material -->
        <%# end %>
      <%# end %>
    <% end %>
  </div>
</div>
</footer>

app/views/materials/_form.html.erb
<%= simple_form_for @material, :html => {:class => "validate"} do |f| %>
  <%= f.error_notification %>

  <table class="table table-condensed">
    <thead>
      <tr>
        <th><%= f.label :name %></th>
        <th><%= f.label :material_type %></th>
        <th><%= f.label :cut_spacing, 'Cut Spacing' %></th>
        <th class="show-area"><%= f.label :width, 'Width (inches)' %></th>
        <th class="show-area"><%= f.label :height, 'Height (inches)' %></th>
        <th class="show-length"><%= f.label :length_options, 'Length(s) (inches)' %></th>
        <th class="show-count"><%= f.label :count %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <% size_options = (48..144).step(4).to_a %>
      <% cut_spacing_options = [[get_inches(0.125),0.125], [get_inches(0.25),0.25], [get_inches(0.375),0.375], [get_inches(0.5),0.5],[get_inches(0.625),0.625], [get_inches(0.75),0.75], [get_inches(0.875),0.875], [get_inches(1),1]] %>
      <% if !@materials_edit %>
        <td><%= f.text_field :name, :required => true, :class => 'form-control' %></td>
        <td id="material-type-container"><%= select :material, :material_type, { "Length" => "length", "Area" => "area", "Count" => "count"}, {}, :class => 'form-control' %></td>
      <% else %>
        <td><%= @material.name %></td>
        <td id="material-type-container"><%= @material.material_type %></td>
      <% end %>
        <td><%= f.select :cut_spacing, options_for_select(cut_spacing_options, @material.cut_spacing), {}, :class => 'form-control' %></td>
        <td class="show-area"><%= f.select :width, options_for_select(size_options, @material.width.to_i), {}, :class => 'form-control' %></td>
        <td class="show-area"><%= f.select :height, options_for_select(size_options, @material.height.to_i ), {}, :class => 'form-control' %></td>
        <td class="show-length">
        <div class="btn-group">
          <%= f.select :length_options, size_options, {}, {:multiple => true, :data => {type: 'Lengths'}, :class => 'form-control multiselect-select'} %>
        </div>
        </td>
        <td class="show-count"><%= f.text_field :count, :type => "number", :class => 'form-control' %></td>
      </tr>
    </tbody>
  </table>

  <div class="form-group text-right">
    <%= f.submit "Submit", :data => {'loading-text' => 'Submitting...'}, :class => 'btn btn-success' %>
    <% if @materials_edit %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :material_type %>
    <% end %>
  </div>

<% end %>

app/views/materials/_header.html.erb
<div class="page-header">
  <h2>
    <% if @materials_show %>
      <%= @material.name %>
      <% if @current_role == 'admin' %>
        <%= link_to edit_material_path(@material), :class => 'btn btn-default btn-xs' do %>
          <span class="glyphicon glyphicon-pencil"></span> Edit
        <% end %>
      <% end %>
    <% elsif @materials_new %>
      New Material
    <% elsif @materials_edit %>
      Editing <%= @material.name %>
    <% elsif @materials_index %>
      Materials
    <% end %>
  </h2>
</div>

app/views/materials/_list.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th class="text-center">Type</th>
      <th class="text-center">Cut Spacing</th>
      <th class="text-center">Size / Count</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= link_to material.name, material_path(material) %></td>
        <% this_type = material.material_type %>
        <td class="text-center"><%= this_type %></td>
        <% if material.cut_spacing.presence %>
        <td class="text-center"><%= get_inches(material.cut_spacing) %></td>
        <% else %>
        <td class="text-center">-</td>
        <% end %>
        <% if this_type == 'area' %>
          <td class="text-center"><%= get_inches(material.width) %> &times; <%= get_inches(material.height) %></td>
        <% elsif this_type == 'length' %>
          <td class="text-center">
            <% material.length_options.to_a.each_with_index do |lo, index| %>
              <% if index > 0 %>, <%end%><%= get_inches(lo.to_i) %>
            <% end %>
          </td>
        <% elsif this_type == 'count' %>
          <td class="text-center"><%= material.count %></td>
        <% else %>
          <td class="text-center">-</td>
        <% end %>
        <td class="text-right">
        <% if @current_role == 'admin' %>
          <%= link_to edit_material_path(material), :class => 'btn btn-default btn-xs' do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/materials/_material.html.erb
<% type = material.material_type %>
<p>
  <strong>Type:</strong>
  <%= type %>
</p>
<p>
  <strong>Cut Spacing:</strong>
  <%= get_inches(material.cut_spacing) %>
</p>

<% if type == 'area' %>
<p>
  <strong>Width:</strong>
  <%= get_measurements(material.width) %>
</p>
<p>
  <strong>Height:</strong>
  <%= get_measurements(material.height) %>
</p>
<% elsif type == 'length' %>
<p>
  <% lengths = pluralize(material.length_options.length, "Length") %>
  <strong><%= lengths %>:</strong>
  <% material.length_options.to_a.each_with_index do |lo, index| %>
    <% if index > 0 %>, <%end%><%= get_measurements(lo.to_i) %>
  <%end%>
</p>
<% elsif type == 'count' %>
<p>
  <strong>Count:</strong>
  <%= material.count %>
</p>
<% end %>

app/views/materials/edit.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= render 'footer' %>

app/views/materials/index.html.erb
<%= render 'header' %>
<%= render 'list' %>
<%= render 'footer' %>

app/views/materials/new.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= render 'footer' %>

app/views/materials/show.html.erb
<%= render 'header' %>
<%= render @material %>
<%= render 'footer' %>